mqtt:
  host: "192.168.178.160"
  port: 1883
  topic_base: "logdetective"
  client_id: "logdetective-rpi5"
influxdb:
  host: "192.168.178.120"
  port: 8086
  database: logdetective
  username: loguser
  password: logpass

use_geoip: true  # Enable GeoIP lookup for IP addresses found in logs
geoip_path: /usr/share/GeoIP/GeoLite2-City.mmdb  # Optional override path

verbosity: 1  # 0 = only critical, 1 = suspicious, 2 = all

logs:
  - path: "/var/log/mumble-server/mumble-server.log"
    rule_file: "rules/mumble.yaml"
    mqtt_topic: "logdetective/mumble"
  - path: "/var/log/auth.log"
    rule_file: "rules/ssh.yaml"
    mqtt_topic: "logdetective/ssh"
  - path: "/var/log/ufw.log"
    rule_file: "rules/ufw.yaml"
    mqtt_topic: "logdetective/ufw"
  - path: "/var/log/fail2ban.log"
    rule_file: "rules/fail2ban.yaml"
    mqtt_topic: "logdetective/fail2ban"
  - path: /var/log/minecraft_latest.log
    rule_file: rules/minecraft.yaml
    mqtt_topic: "logdetective/minecraft"
