version: "3.9"

services:
  log_detective:
    build: .
    container_name: log_detective
    restart: unless-stopped
    volumes:
      - /var/log/mumble-server:/var/log/mumble-server:ro
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/psad:/var/log/psad:ro
      - /var/log/ufw:/var/log/ufw:ro
      - /var/log/fail2ban:/var/log/fail2ban:ro
      - ${PWD}/config.yml:/app/config.yml:ro
      - ${PWD}/rules:/app/rules:ro
      - /etc/log_detective/geoip:/usr/share/GeoIP:ro
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1