name: CI Build


on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Build Docker image using build script
        run: |
          chmod +x ./build_log_detective.sh
          ./build_log_detective.sh

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GHCR
        run: |
          if [[ "$GITHUB_REF" == refs/heads/* ]]; then
            VERSION=dev
          else
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}
          docker tag log_detective:latest $IMAGE:$VERSION
          docker push $IMAGE:$VERSION
          docker tag log_detective:latest $IMAGE:latest
          docker push $IMAGE:latest

      - name: Update Release Notes with Docker Image
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Docker image for this release is available at:

            ```bash
            docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ```